---
title: "HW4: Programming"
author: "Ignacia Rivera, Lina Barbosa, Rucha Thakar"
date: "May 23, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r, echo=FALSE}
suppressPackageStartupMessages({
 library(tidyverse) 
})
```

# Creating Dataset example 

```{r monk data}
fish <- c("Cod", "Dab", "Greysole", "Haddock","Hake", "Pollock")
price <- c(3.15, 2.85, 5.56, 2.44, 2.21, 1.59 )
sites <- c("A", "B", "C", "D", "E", "F")

prices <- data.frame(fish, price)
set.seed(1) 
catch <- matrix(data= sample.int(300, size = length(fish)*length(sites), 
                                 replace = TRUE), nrow = length(fish), 
                                 ncol = length(sites))
catch <- data.frame(fish, catch)
colnames(catch) <- c("fish", unique(sites))

```

# Data Visualization

```{r}
knitr::kable(catch)
knitr::kable(prices)
```

# Using fish_function 

```{r}
source('~/Documents/GitHub/Rivera_ESM262/HW4/fish_function.R')

Example <- fish_function(prices = prices, catch = catch, plot = T)
```

## Extract most frequent fish 

```{r}
Example$frequent_fish %>% 
  knitr::kable()

```

## Extract total revenue by site 

```{r}
Example$site_revenue %>% 
  knitr::kable()
```

## The total fisheries sum is `r Example$total_catches`

\clearpage

# Plot

```{r}
Example$plot
```

